/**
 * shadowEnrollment — one-time, account-bound controller enrollment, scope-key
 * wrapping, revocation and key rotation, built purely on {@link ShadowCryptoBackend}.
 *
 * Trust / secrecy contract enforced here (see REPORT threat model):
 *   - Controller & host each hold distinct Ed25519 (signing) + X25519 (agreement)
 *     keys. Private material never leaves the owning tier; only raw public keys,
 *     signatures, and AEAD ciphertext cross the wire.
 *   - The one-time enrollment secret (256-bit) is carried only in the QR/deep-link
 *     bootstrap and proven to the server against a peppered verifier; the server
 *     never stores the plaintext secret and never learns any private key or the
 *     decrypted scope key.
 *   - A transcript hash binds session id, account, host device, both host public
 *     keys, controller device, both controller public keys, relay origin and a
 *     nonce. Every signature and the scope-key wrap are bound to it, so replacing
 *     any bound value invalidates the flow.
 *   - The scope key is freshly generated by the host and wrapped to the controller
 *     X25519 key via transcript-salted HKDF-SHA256 + AES-256-GCM. The relay only
 *     ever transports/stores the ciphertext + public metadata.
 *
 * The compact, exact-keyed wire families (`enrollment-request`, `enrollment-grant`,
 * `device-revocation`, `key-rotation`) defined in `./shadowProtocol` are the SIGNED
 * control notifications; the richer request/grant/key-material records defined here
 * are the transcript + ciphertext the relay stores. Signatures produced here are
 * real Ed25519 signatures (base64url) that also satisfy the protocol decoders.
 */
import {
  base64urlDecode,
  base64urlEncode,
  concatBytes,
  constantTimeEqual,
  keyFingerprint,
  structuredDigest,
  structuredEncode,
  utf8Encode,
  SHADOW_AES_GCM_NONCE_BYTES,
  SHADOW_ENROLLMENT_SECRET_BYTES,
  SHADOW_SCOPE_KEY_BYTES,
  type ShadowCryptoBackend,
  type ShadowKeyPair,
} from './shadowCrypto.js';
import {
  SHADOW_ENROLLMENT_GRANT_MAX_TTL_MS,
  type Fence,
} from './shadowProtocol.js';
import {
  canonicalizeCapabilities,
  capabilitiesCanonicalString,
  type ShadowCapability,
} from './shadowCapabilities.js';

export const SHADOW_ENROLLMENT_SESSION_MAX_TTL_MS = 300_000; // 5 minutes
export const SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME = 'maestro-shadow' as const;
export const SHADOW_ENROLLMENT_BOOTSTRAP_VERSION = 1 as const;

const DOMAIN_TRANSCRIPT = 'maestro.shadow.enroll.transcript.v1';
const DOMAIN_REQUEST_SIG = 'maestro.shadow.enroll.request-sig.v1';
const DOMAIN_GRANT_SIG = 'maestro.shadow.enroll.grant-sig.v1';
const DOMAIN_REVOKE_SIG = 'maestro.shadow.enroll.revoke-sig.v1';
const DOMAIN_ROTATE_SIG = 'maestro.shadow.enroll.rotate-sig.v1';
const DOMAIN_SECRET_BINDING = 'maestro.shadow.enroll.secret-binding.v1';
const DOMAIN_SECRET_VERIFIER = 'maestro.shadow.enroll.secret-verifier.v1';
const DOMAIN_WRAP_INFO = 'maestro.shadow.enroll.wrap.v1';
const DOMAIN_WRAP_AAD = 'maestro.shadow.enroll.wrap-aad.v1';

// ---------------------------------------------------------------------------
// Identities
// ---------------------------------------------------------------------------

export interface ShadowIdentityKeys {
  readonly signing: ShadowKeyPair;
  readonly agreement: ShadowKeyPair;
}

export interface ShadowIdentityPublic {
  readonly deviceId: string;
  readonly signingPublicKey: Uint8Array;
  readonly agreementPublicKey: Uint8Array;
  readonly signingKeyId: string;
  readonly agreementKeyId: string;
}

export interface ShadowIdentity extends ShadowIdentityPublic {
  readonly keys: ShadowIdentityKeys;
}

/** Generate a fresh device identity (distinct Ed25519 + X25519 keys) from the CSPRNG. */
export async function generateShadowIdentity(backend: ShadowCryptoBackend, deviceId: string): Promise<ShadowIdentity> {
  const signing = await backend.generateSigningKeyPair();
  const agreement = await backend.generateAgreementKeyPair();
  return materializeIdentity(backend, deviceId, { signing, agreement });
}

/** Rebuild the public projection + key ids for a persisted identity keypair. */
export async function materializeIdentity(backend: ShadowCryptoBackend, deviceId: string, keys: ShadowIdentityKeys): Promise<ShadowIdentity> {
  const signingKeyId = await keyFingerprint(backend, 'sign', keys.signing.publicKey);
  const agreementKeyId = await keyFingerprint(backend, 'agree', keys.agreement.publicKey);
  return {
    deviceId,
    keys,
    signingPublicKey: keys.signing.publicKey,
    agreementPublicKey: keys.agreement.publicKey,
    signingKeyId,
    agreementKeyId,
  };
}

// ---------------------------------------------------------------------------
// One-time secret + verifier
// ---------------------------------------------------------------------------

export interface EnrollmentSecretVerifier {
  readonly salt: string; // base64url
  readonly verifier: string; // base64url, peppered HMAC — safe at rest
}

/** Binding hash of the one-time secret to its session + account (never the raw secret). */
async function secretBinding(backend: ShadowCryptoBackend, sessionId: string, accountId: string, secret: Uint8Array): Promise<Uint8Array> {
  const secretDigest = await backend.sha256(secret);
  return structuredDigest(backend, DOMAIN_SECRET_BINDING, [sessionId, accountId, secretDigest]);
}

/**
 * Server-side verifier of the one-time secret: HMAC(serverPepper, salt || binding).
 * Stored at rest; the plaintext secret is never persisted. `pepper` is a
 * server-only key; `salt` is per-session random.
 */
export async function makeEnrollmentSecretVerifier(
  backend: ShadowCryptoBackend,
  input: { sessionId: string; accountId: string; secret: Uint8Array; salt: Uint8Array; pepper: Uint8Array },
): Promise<EnrollmentSecretVerifier> {
  const binding = await secretBinding(backend, input.sessionId, input.accountId, input.secret);
  const mac = await backend.hmacSha256(input.pepper, structuredEncode(DOMAIN_SECRET_VERIFIER, [input.sessionId, input.accountId, input.salt, binding]));
  return { salt: base64urlEncode(input.salt), verifier: base64urlEncode(mac) };
}

/** Constant-time verification of a presented secret against the stored peppered verifier. */
export async function verifyEnrollmentSecret(
  backend: ShadowCryptoBackend,
  input: { sessionId: string; accountId: string; presentedSecret: Uint8Array; stored: EnrollmentSecretVerifier; pepper: Uint8Array },
): Promise<boolean> {
  let salt: Uint8Array;
  let expected: Uint8Array;
  try {
    salt = base64urlDecode(input.stored.salt);
    expected = base64urlDecode(input.stored.verifier);
  } catch {
    return false;
  }
  const binding = await secretBinding(backend, input.sessionId, input.accountId, input.presentedSecret);
  const mac = await backend.hmacSha256(input.pepper, structuredEncode(DOMAIN_SECRET_VERIFIER, [input.sessionId, input.accountId, salt, binding]));
  return constantTimeEqual(mac, expected);
}

// ---------------------------------------------------------------------------
// Bootstrap (QR / deep link)
// ---------------------------------------------------------------------------

export interface EnrollmentBootstrap {
  readonly scheme: typeof SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME;
  readonly v: typeof SHADOW_ENROLLMENT_BOOTSTRAP_VERSION;
  readonly sessionId: string;
  readonly accountId: string;
  readonly hostDeviceId: string;
  readonly hostSigningKeyId: string;
  readonly hostSigningPublicKey: string; // base64url raw
  readonly hostAgreementPublicKey: string; // base64url raw
  readonly relayOrigin: string;
  readonly secret: string; // base64url one-time secret (bootstrap only; not a key)
  readonly expiresAt: number;
}

export interface EnrollmentSessionCreation {
  readonly sessionId: string;
  readonly bootstrap: EnrollmentBootstrap;
  /** Server-stored record — carries NO plaintext secret and NO private keys. */
  readonly serverRecord: EnrollmentServerRecord;
  /** The raw secret is returned once to the caller (host) to render the QR, then discarded. */
  readonly secret: Uint8Array;
}

export interface EnrollmentServerRecord {
  readonly sessionId: string;
  readonly accountId: string;
  readonly hostDeviceId: string;
  readonly hostSigningKeyId: string;
  readonly relayOrigin: string;
  readonly secretVerifier: EnrollmentSecretVerifier;
  readonly createdAt: number;
  readonly expiresAt: number;
}

/**
 * Host-side session creation. Produces the QR bootstrap (with the one-time secret)
 * and the server record (with only the peppered verifier). `idOf` supplies random
 * ids from the caller so the module stays free of ambient time/RNG beyond `backend`.
 */
export async function createEnrollmentSession(
  backend: ShadowCryptoBackend,
  input: {
    host: ShadowIdentityPublic;
    accountId: string;
    relayOrigin: string;
    nowMs: number;
    ttlMs?: number;
    serverPepper: Uint8Array;
    sessionId?: string;
  },
): Promise<EnrollmentSessionCreation> {
  const ttl = Math.min(input.ttlMs ?? SHADOW_ENROLLMENT_SESSION_MAX_TTL_MS, SHADOW_ENROLLMENT_SESSION_MAX_TTL_MS);
  const sessionId = input.sessionId ?? 'es_' + base64urlEncode(backend.randomBytes(18));
  const secret = backend.randomBytes(SHADOW_ENROLLMENT_SECRET_BYTES);
  const salt = backend.randomBytes(16);
  const expiresAt = input.nowMs + ttl;
  const secretVerifier = await makeEnrollmentSecretVerifier(backend, { sessionId, accountId: input.accountId, secret, salt, pepper: input.serverPepper });
  const bootstrap: EnrollmentBootstrap = {
    scheme: SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME,
    v: SHADOW_ENROLLMENT_BOOTSTRAP_VERSION,
    sessionId,
    accountId: input.accountId,
    hostDeviceId: input.host.deviceId,
    hostSigningKeyId: input.host.signingKeyId,
    hostSigningPublicKey: base64urlEncode(input.host.signingPublicKey),
    hostAgreementPublicKey: base64urlEncode(input.host.agreementPublicKey),
    relayOrigin: input.relayOrigin,
    secret: base64urlEncode(secret),
    expiresAt,
  };
  const serverRecord: EnrollmentServerRecord = {
    sessionId,
    accountId: input.accountId,
    hostDeviceId: input.host.deviceId,
    hostSigningKeyId: input.host.signingKeyId,
    relayOrigin: input.relayOrigin,
    secretVerifier,
    createdAt: input.nowMs,
    expiresAt,
  };
  return { sessionId, bootstrap, serverRecord, secret };
}

export function encodeEnrollmentBootstrap(bootstrap: EnrollmentBootstrap): string {
  // Compact, URL-safe deep link. Field order fixed; values are already url-safe.
  const params = new URLSearchParams({
    v: String(bootstrap.v),
    s: bootstrap.sessionId,
    a: bootstrap.accountId,
    h: bootstrap.hostDeviceId,
    hk: bootstrap.hostSigningKeyId,
    hsp: bootstrap.hostSigningPublicKey,
    hap: bootstrap.hostAgreementPublicKey,
    o: bootstrap.relayOrigin,
    sec: bootstrap.secret,
    e: String(bootstrap.expiresAt),
  });
  return `${SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME}://enroll?${params.toString()}`;
}

export function decodeEnrollmentBootstrap(
  value: string,
  options: { allowedOrigins: readonly string[]; nowMs: number },
): { ok: true; value: EnrollmentBootstrap } | { ok: false; reason: string } {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return { ok: false, reason: 'bad-url' };
  }
  if (url.protocol !== `${SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME}:`) return { ok: false, reason: 'bad-scheme' };
  if (url.host !== 'enroll' && url.pathname.replace(/^\/+/, '') !== 'enroll') return { ok: false, reason: 'bad-action' };
  const q = url.searchParams;
  const v = Number(q.get('v'));
  if (v !== SHADOW_ENROLLMENT_BOOTSTRAP_VERSION) return { ok: false, reason: 'bad-version' };
  const get = (k: string) => q.get(k) ?? '';
  const relayOrigin = get('o');
  if (!options.allowedOrigins.includes(relayOrigin)) return { ok: false, reason: 'origin-not-allowed' };
  const expiresAt = Number(get('e'));
  if (!Number.isSafeInteger(expiresAt)) return { ok: false, reason: 'bad-expiry' };
  if (options.nowMs >= expiresAt) return { ok: false, reason: 'expired' };
  if (expiresAt - options.nowMs > SHADOW_ENROLLMENT_SESSION_MAX_TTL_MS + 60_000) return { ok: false, reason: 'expiry-too-far' };
  const idRe = /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/;
  const b64 = /^[A-Za-z0-9_-]+$/;
  const sessionId = get('s'), accountId = get('a'), hostDeviceId = get('h'), hostSigningKeyId = get('hk');
  const hsp = get('hsp'), hap = get('hap'), secret = get('sec');
  if (![sessionId, accountId, hostDeviceId, hostSigningKeyId].every((x) => idRe.test(x))) return { ok: false, reason: 'bad-id' };
  if (![hsp, hap, secret].every((x) => b64.test(x))) return { ok: false, reason: 'bad-material' };
  let secretBytes: Uint8Array, sp: Uint8Array, ap: Uint8Array;
  try {
    secretBytes = base64urlDecode(secret); sp = base64urlDecode(hsp); ap = base64urlDecode(hap);
  } catch {
    return { ok: false, reason: 'bad-b64' };
  }
  if (secretBytes.length !== SHADOW_ENROLLMENT_SECRET_BYTES || sp.length !== 32 || ap.length !== 32) return { ok: false, reason: 'bad-length' };
  return {
    ok: true,
    value: {
      scheme: SHADOW_ENROLLMENT_BOOTSTRAP_SCHEME,
      v: SHADOW_ENROLLMENT_BOOTSTRAP_VERSION,
      sessionId, accountId, hostDeviceId, hostSigningKeyId,
      hostSigningPublicKey: hsp, hostAgreementPublicKey: hap,
      relayOrigin, secret, expiresAt,
    },
  };
}

// ---------------------------------------------------------------------------
// Transcript
// ---------------------------------------------------------------------------

export interface EnrollmentTranscriptInput {
  sessionId: string;
  accountId: string;
  hostDeviceId: string;
  hostSigningPublicKey: Uint8Array;
  hostAgreementPublicKey: Uint8Array;
  controllerDeviceId: string;
  controllerSigningPublicKey: Uint8Array;
  controllerAgreementPublicKey: Uint8Array;
  relayOrigin: string;
  nonce: Uint8Array;
}

export async function enrollmentTranscriptHash(backend: ShadowCryptoBackend, t: EnrollmentTranscriptInput): Promise<Uint8Array> {
  return structuredDigest(backend, DOMAIN_TRANSCRIPT, [
    t.sessionId, t.accountId, t.hostDeviceId,
    t.hostSigningPublicKey, t.hostAgreementPublicKey,
    t.controllerDeviceId, t.controllerSigningPublicKey, t.controllerAgreementPublicKey,
    t.relayOrigin, t.nonce,
  ]);
}

// ---------------------------------------------------------------------------
// Controller enrollment request
// ---------------------------------------------------------------------------

export interface EnrollmentRequest {
  readonly v: number;
  readonly sessionId: string;
  readonly accountId: string;
  readonly controllerDeviceId: string;
  readonly controllerSigningKeyId: string;
  readonly controllerAgreementKeyId: string;
  readonly signingPublicKey: string; // base64url raw
  readonly agreementPublicKey: string; // base64url raw
  readonly nonce: string; // base64url
  readonly requestedAt: number;
  readonly transcriptHash: string; // base64url
  /**
   * Canonical (sorted, deduped, bounded) capability set the CONTROLLER requests,
   * bound into the controller-signed request proof. OPTIONAL for byte-additive
   * legacy compatibility: a request with no field is treated as `account.read` only.
   * The host may only ever approve a subset of this verified set (see approveEnrollment).
   */
  readonly requestedCapabilities?: readonly ShadowCapability[];
  readonly signature: string; // base64url Ed25519 over request transcript
}

async function requestSigningInput(backend: ShadowCryptoBackend, r: Omit<EnrollmentRequest, 'signature'>, bootstrap: { hostSigningPublicKey: Uint8Array; hostAgreementPublicKey: Uint8Array; relayOrigin: string }): Promise<Uint8Array> {
  const parts: Array<string | number | Uint8Array> = [
    r.sessionId, r.accountId, r.controllerDeviceId,
    base64urlDecode(r.signingPublicKey), base64urlDecode(r.agreementPublicKey),
    bootstrap.hostSigningPublicKey, bootstrap.hostAgreementPublicKey, bootstrap.relayOrigin,
    base64urlDecode(r.nonce), r.requestedAt, base64urlDecode(r.transcriptHash),
  ];
  // BYTE-ADDITIVE: a legacy request (no requestedCapabilities) signs exactly as before;
  // a request that carries them binds their canonical string, so any add/remove/unknown
  // breaks the controller signature. Invalid → poison marker that can never verify.
  if (r.requestedCapabilities !== undefined) {
    const canon = canonicalizeCapabilities(r.requestedCapabilities);
    parts.push(canon.ok ? `req:${capabilitiesCanonicalString(canon.capabilities)}` : '\u0000invalid-requested-capabilities');
  }
  return structuredEncode(DOMAIN_REQUEST_SIG, parts);
}

/**
 * Controller builds and signs an enrollment request from a validated bootstrap.
 * The controller proves control of its signing private key over the transcript.
 * The raw one-time secret is returned separately for presentation to the server
 * (never embedded in the signed request that is forwarded to the host).
 */
export async function buildEnrollmentRequest(
  backend: ShadowCryptoBackend,
  input: { controller: ShadowIdentity; bootstrap: EnrollmentBootstrap; nowMs: number; nonce?: Uint8Array; requestedCapabilities?: readonly ShadowCapability[] },
): Promise<{ request: EnrollmentRequest; presentedSecret: Uint8Array }> {
  const nonce = input.nonce ?? backend.randomBytes(16);
  let requestedCapabilities: readonly ShadowCapability[] | undefined;
  if (input.requestedCapabilities !== undefined) {
    const canon = canonicalizeCapabilities(input.requestedCapabilities);
    if (!canon.ok) throw new Error(`buildEnrollmentRequest: invalid requestedCapabilities (${canon.reason})`);
    requestedCapabilities = canon.capabilities;
  }
  const hostSigningPublicKey = base64urlDecode(input.bootstrap.hostSigningPublicKey);
  const hostAgreementPublicKey = base64urlDecode(input.bootstrap.hostAgreementPublicKey);
  const transcript = await enrollmentTranscriptHash(backend, {
    sessionId: input.bootstrap.sessionId,
    accountId: input.bootstrap.accountId,
    hostDeviceId: input.bootstrap.hostDeviceId,
    hostSigningPublicKey,
    hostAgreementPublicKey,
    controllerDeviceId: input.controller.deviceId,
    controllerSigningPublicKey: input.controller.signingPublicKey,
    controllerAgreementPublicKey: input.controller.agreementPublicKey,
    relayOrigin: input.bootstrap.relayOrigin,
    nonce,
  });
  const unsigned: Omit<EnrollmentRequest, 'signature'> = {
    v: SHADOW_ENROLLMENT_BOOTSTRAP_VERSION,
    sessionId: input.bootstrap.sessionId,
    accountId: input.bootstrap.accountId,
    controllerDeviceId: input.controller.deviceId,
    controllerSigningKeyId: input.controller.signingKeyId,
    controllerAgreementKeyId: input.controller.agreementKeyId,
    signingPublicKey: base64urlEncode(input.controller.signingPublicKey),
    agreementPublicKey: base64urlEncode(input.controller.agreementPublicKey),
    nonce: base64urlEncode(nonce),
    requestedAt: input.nowMs,
    transcriptHash: base64urlEncode(transcript),
    ...(requestedCapabilities ? { requestedCapabilities } : {}),
  };
  const sigInput = await requestSigningInput(backend, unsigned, { hostSigningPublicKey, hostAgreementPublicKey, relayOrigin: input.bootstrap.relayOrigin });
  const signature = await backend.sign(input.controller.keys.signing.privateKey, sigInput);
  return {
    request: { ...unsigned, signature: base64urlEncode(signature) },
    presentedSecret: base64urlDecode(input.bootstrap.secret),
  };
}

/**
 * Host/server-side verification of an enrollment request: signature over the
 * transcript by the claimed controller signing key, key-id ↔ public-key binding,
 * account/session/host binding, transcript recomputation from the ACTUAL public
 * keys, and TTL. Returns the verified transcript hash on success.
 */
export async function verifyEnrollmentRequest(
  backend: ShadowCryptoBackend,
  input: { request: EnrollmentRequest; bootstrap: EnrollmentBootstrap; expectedAccountId: string; nowMs: number },
): Promise<{ ok: true; transcriptHash: Uint8Array; controllerSigningPublicKey: Uint8Array; controllerAgreementPublicKey: Uint8Array; requestedCapabilities: ShadowCapability[] } | { ok: false; reason: string }> {
  const r = input.request;
  if (r.v !== SHADOW_ENROLLMENT_BOOTSTRAP_VERSION) return { ok: false, reason: 'bad-version' };
  // Canonicalise the presented requested-capability set (undefined → account.read
  // legacy floor); fail closed on unknown/oversized BEFORE trusting the request.
  const reqCaps = canonicalizeCapabilities(r.requestedCapabilities);
  if (!reqCaps.ok) return { ok: false, reason: `bad-requested-capabilities:${reqCaps.reason}` };
  if (r.sessionId !== input.bootstrap.sessionId) return { ok: false, reason: 'session-mismatch' };
  if (r.accountId !== input.bootstrap.accountId || r.accountId !== input.expectedAccountId) return { ok: false, reason: 'account-mismatch' };
  if (input.nowMs >= input.bootstrap.expiresAt) return { ok: false, reason: 'expired' };
  let signingPub: Uint8Array, agreementPub: Uint8Array, nonce: Uint8Array, claimedTranscript: Uint8Array, signature: Uint8Array;
  try {
    signingPub = base64urlDecode(r.signingPublicKey);
    agreementPub = base64urlDecode(r.agreementPublicKey);
    nonce = base64urlDecode(r.nonce);
    claimedTranscript = base64urlDecode(r.transcriptHash);
    signature = base64urlDecode(r.signature);
  } catch {
    return { ok: false, reason: 'bad-b64' };
  }
  if (signingPub.length !== 32 || agreementPub.length !== 32) return { ok: false, reason: 'bad-key-length' };
  const signingKeyId = await keyFingerprint(backend, 'sign', signingPub);
  const agreementKeyId = await keyFingerprint(backend, 'agree', agreementPub);
  if (signingKeyId !== r.controllerSigningKeyId || agreementKeyId !== r.controllerAgreementKeyId) return { ok: false, reason: 'key-id-mismatch' };
  const hostSigningPublicKey = base64urlDecode(input.bootstrap.hostSigningPublicKey);
  const hostAgreementPublicKey = base64urlDecode(input.bootstrap.hostAgreementPublicKey);
  const recomputed = await enrollmentTranscriptHash(backend, {
    sessionId: r.sessionId, accountId: r.accountId, hostDeviceId: input.bootstrap.hostDeviceId,
    hostSigningPublicKey, hostAgreementPublicKey,
    controllerDeviceId: r.controllerDeviceId, controllerSigningPublicKey: signingPub, controllerAgreementPublicKey: agreementPub,
    relayOrigin: input.bootstrap.relayOrigin, nonce,
  });
  if (!constantTimeEqual(recomputed, claimedTranscript)) return { ok: false, reason: 'transcript-mismatch' };
  const sigInput = await requestSigningInput(backend, { ...r }, { hostSigningPublicKey, hostAgreementPublicKey, relayOrigin: input.bootstrap.relayOrigin });
  const good = await backend.verify(signingPub, sigInput, signature);
  if (!good) return { ok: false, reason: 'bad-signature' };
  return { ok: true, transcriptHash: recomputed, controllerSigningPublicKey: signingPub, controllerAgreementPublicKey: agreementPub, requestedCapabilities: reqCaps.capabilities };
}

// ---------------------------------------------------------------------------
// Grant + scope-key wrap
// ---------------------------------------------------------------------------

export interface EnrollmentGrantMessage {
  readonly family: 'enrollment-grant';
  readonly v: 1;
  readonly fence: Fence;
  readonly controllerDeviceId: string;
  readonly grantId: string;
  readonly expiresAt: number;
  readonly keyId: string;
  readonly signedAt: number;
  /**
   * Host-approved, canonical (sorted, deduped, bounded) capability set bound into
   * the grant signature. OPTIONAL for wire/byte compatibility: a grant with no
   * capability field is a LEGACY grant treated as `account.read` ONLY at the check
   * layer. When present it is bound into {@link grantSigningInput}, so any
   * tamper/downgrade/extra/unknown capability breaks the signature.
   */
  readonly capabilities?: readonly ShadowCapability[];
  readonly signature: string;
}

export interface EnrollmentKeyMaterial {
  readonly sessionId: string;
  readonly grantId: string;
  readonly keyId: string;
  readonly controllerDeviceId: string;
  readonly wrapNonce: string; // base64url
  readonly wrappedScopeKey: string; // base64url AES-256-GCM ciphertext+tag
  readonly transcriptHash: string; // base64url
  readonly createdAt: number;
}

export interface EnrollmentApproval {
  readonly grant: EnrollmentGrantMessage;
  readonly keyMaterial: EnrollmentKeyMaterial;
  /** Returned to the host runtime to seed the shared scope key for existing controllers. */
  readonly scopeKey: Uint8Array;
  readonly scopeKeyId: string;
  /**
   * Canonical host-approved capability set bound into the grant, or `undefined` for
   * a legacy grant (treated as `account.read`). Surfaced so the host local record and
   * the server public metadata can persist the exact audited set.
   */
  readonly capabilities?: readonly ShadowCapability[];
}

async function grantSigningInput(g: Omit<EnrollmentGrantMessage, 'signature'>, transcriptHash: Uint8Array): Promise<Uint8Array> {
  const parts: Array<string | number | Uint8Array> = [
    g.fence.accountId, g.fence.scopeId, g.fence.hostDeviceId, g.fence.epoch, g.fence.leaseId,
    g.controllerDeviceId, g.grantId, g.keyId, g.expiresAt, g.signedAt, transcriptHash,
  ];
  // BYTE-ADDITIVE capability binding: a legacy grant with NO capability field signs
  // exactly as before (nothing appended), preserving accepted-source signatures. A
  // grant that DOES carry capabilities binds their canonical string, so any
  // add/remove/unknown breaks the signature. An unknown/oversized set is bound to a
  // poison marker the host could never have signed → fail-closed on verify.
  if (g.capabilities !== undefined) {
    const canon = canonicalizeCapabilities(g.capabilities);
    parts.push(canon.ok ? capabilitiesCanonicalString(canon.capabilities) : '\u0000invalid-capabilities');
  }
  return structuredEncode(DOMAIN_GRANT_SIG, parts);
}

async function wrapKeyFor(
  backend: ShadowCryptoBackend,
  input: { hostAgreementPrivate: Uint8Array; controllerAgreementPublic: Uint8Array; transcriptHash: Uint8Array; fence: Fence; controllerDeviceId: string; grantId: string; keyId: string },
): Promise<Uint8Array> {
  const shared = await backend.deriveSharedSecret(input.hostAgreementPrivate, input.controllerAgreementPublic);
  const info = structuredEncode(DOMAIN_WRAP_INFO, [input.fence.accountId, input.fence.scopeId, input.fence.hostDeviceId, input.fence.epoch, input.controllerDeviceId, input.grantId, input.keyId]);
  return backend.hkdfSha256(shared, input.transcriptHash, info, 32);
}

function wrapAad(transcriptHash: Uint8Array, keyId: string, controllerDeviceId: string, grantId: string): Uint8Array {
  return concatBytes(utf8Encode(DOMAIN_WRAP_AAD), transcriptHash, utf8Encode(keyId), utf8Encode(controllerDeviceId), utf8Encode(grantId));
}

/**
 * Host approval: generate a fresh scope key, sign the enrollment grant, and wrap
 * the scope key to the controller X25519 key with transcript-salted HKDF + AES-GCM.
 * The caller (host runtime) must have already obtained explicit operator approval
 * bound to this exact session/transcript/account/controller.
 */
export async function approveEnrollment(
  backend: ShadowCryptoBackend,
  input: {
    host: ShadowIdentity;
    fence: Fence;
    controllerDeviceId: string;
    controllerAgreementPublicKey: Uint8Array;
    transcriptHash: Uint8Array;
    sessionId: string;
    nowMs: number;
    ttlMs?: number;
    grantId?: string;
    scopeKey?: Uint8Array; // when rotating/reusing; otherwise freshly generated
    /**
     * Host-approved capability set (least privilege). When omitted the grant is a
     * LEGACY grant (no capability field) treated as `account.read` only. The set is
     * canonicalised here before binding; an invalid set throws (host bug), never
     * silently downgrades.
     */
    capabilities?: readonly ShadowCapability[];
    /**
     * The cryptographically-VERIFIED requested set (from `verifyEnrollmentRequest`).
     * When present, the host-approved `capabilities` MUST be a subset (plus the
     * `account.read` read floor) — the host can never approve an unrequested elevated
     * capability, closing self-escalation. Expansion requires a NEW signed request.
     */
    requestedCapabilities?: readonly ShadowCapability[];
  },
): Promise<EnrollmentApproval> {
  const ttl = Math.min(input.ttlMs ?? SHADOW_ENROLLMENT_GRANT_MAX_TTL_MS, SHADOW_ENROLLMENT_GRANT_MAX_TTL_MS);
  const scopeKey = input.scopeKey ?? backend.randomBytes(SHADOW_SCOPE_KEY_BYTES);
  const scopeKeyId = 'wk_' + base64urlEncode(await structuredDigest(backend, 'maestro.shadow.scope-key.v1', [input.fence.accountId, input.fence.scopeId, scopeKey]));
  const grantId = input.grantId ?? 'eg_' + base64urlEncode(backend.randomBytes(18));
  let capabilities: readonly ShadowCapability[] | undefined;
  if (input.capabilities !== undefined) {
    const canon = canonicalizeCapabilities(input.capabilities);
    if (!canon.ok) throw new Error(`approveEnrollment: invalid capabilities (${canon.reason})`);
    if (input.requestedCapabilities !== undefined) {
      const req = canonicalizeCapabilities(input.requestedCapabilities);
      if (!req.ok) throw new Error(`approveEnrollment: invalid requestedCapabilities (${req.reason})`);
      const requested = new Set(req.capabilities);
      for (const c of canon.capabilities) {
        if (c !== 'account.read' && !requested.has(c)) throw new Error(`approveEnrollment: approved capability ${c} exceeds the verified requested set`);
      }
    }
    capabilities = canon.capabilities;
  }
  const unsigned: Omit<EnrollmentGrantMessage, 'signature'> = {
    family: 'enrollment-grant',
    v: 1,
    fence: input.fence,
    controllerDeviceId: input.controllerDeviceId,
    grantId,
    expiresAt: input.nowMs + ttl,
    keyId: scopeKeyId,
    signedAt: input.nowMs,
    ...(capabilities ? { capabilities } : {}),
  };
  const signature = await backend.sign(input.host.keys.signing.privateKey, await grantSigningInput(unsigned, input.transcriptHash));
  const wrapKey = await wrapKeyFor(backend, {
    hostAgreementPrivate: input.host.keys.agreement.privateKey,
    controllerAgreementPublic: input.controllerAgreementPublicKey,
    transcriptHash: input.transcriptHash, fence: input.fence, controllerDeviceId: input.controllerDeviceId, grantId, keyId: scopeKeyId,
  });
  const wrapNonce = backend.randomBytes(SHADOW_AES_GCM_NONCE_BYTES);
  const wrapped = await backend.aesGcmSeal(wrapKey, wrapNonce, scopeKey, wrapAad(input.transcriptHash, scopeKeyId, input.controllerDeviceId, grantId));
  return {
    grant: { ...unsigned, signature: base64urlEncode(signature) },
    keyMaterial: {
      sessionId: input.sessionId, grantId, keyId: scopeKeyId, controllerDeviceId: input.controllerDeviceId,
      wrapNonce: base64urlEncode(wrapNonce), wrappedScopeKey: base64urlEncode(wrapped),
      transcriptHash: base64urlEncode(input.transcriptHash), createdAt: input.nowMs,
    },
    scopeKey, scopeKeyId,
    ...(capabilities ? { capabilities } : {}),
  };
}

/**
 * Relay/host-side verification of an enrollment grant's Ed25519 signature
 * against a known host signing public key and the bound transcript hash. Unlike
 * {@link acceptEnrollmentGrant} this does NOT unwrap the scope key (the relay has
 * no private key and must never see plaintext); it only proves the grant was
 * signed by the host over this exact transcript + fence + controller binding, so
 * the relay can refuse to persist a forged or mis-bound grant.
 */
export async function verifyEnrollmentGrantSignature(
  backend: ShadowCryptoBackend,
  hostSigningPublicKey: Uint8Array,
  grant: EnrollmentGrantMessage,
  transcriptHash: Uint8Array,
): Promise<boolean> {
  if (grant.family !== 'enrollment-grant' || grant.v !== 1) return false;
  let signature: Uint8Array;
  try {
    signature = base64urlDecode(grant.signature);
  } catch {
    return false;
  }
  const { signature: _sig, ...unsigned } = grant;
  return backend.verify(hostSigningPublicKey, await grantSigningInput(unsigned, transcriptHash), signature);
}

/**
 * Controller-side grant verification + scope-key unwrap. Verifies the host
 * signature (against the bootstrap host signing key), transcript binding,
 * account/controller/fence/TTL, then unwraps the scope key. Returns the scope
 * key (to be stored ONLY in SecureStore) on success.
 */
export async function acceptEnrollmentGrant(
  backend: ShadowCryptoBackend,
  input: {
    controller: ShadowIdentity;
    bootstrap: EnrollmentBootstrap;
    grant: EnrollmentGrantMessage;
    keyMaterial: EnrollmentKeyMaterial;
    transcriptHash: Uint8Array;
    nowMs: number;
  },
): Promise<{ ok: true; scopeKey: Uint8Array; scopeKeyId: string; fence: Fence; capabilities: ShadowCapability[] } | { ok: false; reason: string }> {
  const g = input.grant;
  const km = input.keyMaterial;
  if (g.family !== 'enrollment-grant' || g.v !== 1) return { ok: false, reason: 'bad-grant' };
  if (g.controllerDeviceId !== input.controller.deviceId || km.controllerDeviceId !== input.controller.deviceId) return { ok: false, reason: 'controller-mismatch' };
  if (g.fence.accountId !== input.bootstrap.accountId) return { ok: false, reason: 'account-mismatch' };
  if (g.keyId !== km.keyId) return { ok: false, reason: 'key-id-mismatch' };
  if (input.nowMs >= g.expiresAt) return { ok: false, reason: 'expired' };
  // Canonicalise the presented capability set (undefined → account.read legacy floor)
  // and fail closed on unknown/oversized BEFORE trusting the grant.
  const caps = canonicalizeCapabilities(g.capabilities);
  if (!caps.ok) return { ok: false, reason: `bad-capabilities:${caps.reason}` };
  let transcriptFromKm: Uint8Array, signature: Uint8Array, wrapNonce: Uint8Array, wrapped: Uint8Array;
  try {
    transcriptFromKm = base64urlDecode(km.transcriptHash);
    signature = base64urlDecode(g.signature);
    wrapNonce = base64urlDecode(km.wrapNonce);
    wrapped = base64urlDecode(km.wrappedScopeKey);
  } catch {
    return { ok: false, reason: 'bad-b64' };
  }
  if (!constantTimeEqual(transcriptFromKm, input.transcriptHash)) return { ok: false, reason: 'transcript-mismatch' };
  const hostSigningPub = base64urlDecode(input.bootstrap.hostSigningPublicKey);
  const good = await backend.verify(hostSigningPub, await grantSigningInput(g, input.transcriptHash), signature);
  if (!good) return { ok: false, reason: 'bad-signature' };
  const wrapKey = await wrapKeyFor(backend, {
    hostAgreementPrivate: input.controller.keys.agreement.privateKey,
    controllerAgreementPublic: base64urlDecode(input.bootstrap.hostAgreementPublicKey),
    transcriptHash: input.transcriptHash, fence: g.fence, controllerDeviceId: g.controllerDeviceId, grantId: g.grantId, keyId: g.keyId,
  });
  const scopeKey = await backend.aesGcmOpen(wrapKey, wrapNonce, wrapped, wrapAad(input.transcriptHash, g.keyId, g.controllerDeviceId, g.grantId));
  if (!scopeKey || scopeKey.length !== SHADOW_SCOPE_KEY_BYTES) return { ok: false, reason: 'unwrap-failed' };
  return { ok: true, scopeKey, scopeKeyId: g.keyId, fence: g.fence, capabilities: caps.capabilities };
}

/**
 * Controller-side unwrap of a ROTATED scope key (post-revocation rotation).
 *
 * When a controller is revoked, the host rotates the scope key and rewraps it to
 * each remaining controller against that controller's EXISTING grantId. The relay
 * stores only the new ciphertext (keyId / wrapNonce / wrappedScopeKey) on the
 * existing grant row and does NOT re-sign the grant, so a re-poll returns a grant
 * whose Ed25519 signature no longer matches the new keyId. Trust here rests on the
 * AEAD wrap itself: the wrap key is HKDF(ECDH(hostAgreementPriv, controllerAgreementPub),
 * salt=transcriptHash, info=…) with AAD binding transcript+keyId+controller+grantId,
 * so only the genuine host could have produced a ciphertext that opens — a successful
 * unwrap is cryptographic proof of host authorship. This helper performs the
 * transcript/account/controller/keyId/TTL checks + the authenticated unwrap, WITHOUT
 * the (now-stale) grant signature check. `acceptEnrollmentGrant` (initial enrollment)
 * is unchanged and still requires the signature.
 */
export async function unwrapRotatedScopeKey(
  backend: ShadowCryptoBackend,
  input: {
    controller: ShadowIdentity;
    bootstrap: EnrollmentBootstrap;
    grant: EnrollmentGrantMessage;
    keyMaterial: EnrollmentKeyMaterial;
    transcriptHash: Uint8Array;
    nowMs: number;
  },
): Promise<{ ok: true; scopeKey: Uint8Array; scopeKeyId: string; fence: Fence; capabilities: ShadowCapability[] } | { ok: false; reason: string }> {
  const g = input.grant;
  const km = input.keyMaterial;
  if (g.family !== 'enrollment-grant' || g.v !== 1) return { ok: false, reason: 'bad-grant' };
  if (g.controllerDeviceId !== input.controller.deviceId || km.controllerDeviceId !== input.controller.deviceId) return { ok: false, reason: 'controller-mismatch' };
  if (g.fence.accountId !== input.bootstrap.accountId) return { ok: false, reason: 'account-mismatch' };
  if (g.keyId !== km.keyId) return { ok: false, reason: 'key-id-mismatch' };
  if (input.nowMs >= g.expiresAt) return { ok: false, reason: 'expired' };
  const caps = canonicalizeCapabilities(g.capabilities);
  if (!caps.ok) return { ok: false, reason: `bad-capabilities:${caps.reason}` };
  let transcriptFromKm: Uint8Array, wrapNonce: Uint8Array, wrapped: Uint8Array;
  try {
    transcriptFromKm = base64urlDecode(km.transcriptHash);
    wrapNonce = base64urlDecode(km.wrapNonce);
    wrapped = base64urlDecode(km.wrappedScopeKey);
  } catch {
    return { ok: false, reason: 'bad-b64' };
  }
  if (!constantTimeEqual(transcriptFromKm, input.transcriptHash)) return { ok: false, reason: 'transcript-mismatch' };
  const wrapKey = await wrapKeyFor(backend, {
    hostAgreementPrivate: input.controller.keys.agreement.privateKey,
    controllerAgreementPublic: base64urlDecode(input.bootstrap.hostAgreementPublicKey),
    transcriptHash: input.transcriptHash, fence: g.fence, controllerDeviceId: g.controllerDeviceId, grantId: g.grantId, keyId: g.keyId,
  });
  const scopeKey = await backend.aesGcmOpen(wrapKey, wrapNonce, wrapped, wrapAad(input.transcriptHash, g.keyId, g.controllerDeviceId, g.grantId));
  if (!scopeKey || scopeKey.length !== SHADOW_SCOPE_KEY_BYTES) return { ok: false, reason: 'unwrap-failed' };
  return { ok: true, scopeKey, scopeKeyId: g.keyId, fence: g.fence, capabilities: caps.capabilities };
}

// ---------------------------------------------------------------------------
// Revocation + key rotation
// ---------------------------------------------------------------------------

export interface DeviceRevocationMessage {
  readonly family: 'device-revocation';
  readonly v: 1;
  readonly fence: Fence;
  readonly controllerDeviceId: string;
  readonly revokedAt: number;
  readonly keyRotationId: string;
  readonly signature: string;
}

export interface KeyRotationMessage {
  readonly family: 'key-rotation';
  readonly v: 1;
  readonly fence: Fence;
  readonly keyId: string;
  readonly previousKeyId: string;
  readonly effectiveSeq: number;
  readonly createdAt: number;
  readonly signature: string;
}

function revokeSigningInput(m: Omit<DeviceRevocationMessage, 'signature'>): Uint8Array {
  return structuredEncode(DOMAIN_REVOKE_SIG, [m.fence.accountId, m.fence.scopeId, m.fence.hostDeviceId, m.fence.epoch, m.fence.leaseId, m.controllerDeviceId, m.revokedAt, m.keyRotationId]);
}

function rotateSigningInput(m: Omit<KeyRotationMessage, 'signature'>): Uint8Array {
  return structuredEncode(DOMAIN_ROTATE_SIG, [m.fence.accountId, m.fence.scopeId, m.fence.hostDeviceId, m.fence.epoch, m.fence.leaseId, m.keyId, m.previousKeyId, m.effectiveSeq, m.createdAt]);
}

export async function signDeviceRevocation(backend: ShadowCryptoBackend, host: ShadowIdentity, m: Omit<DeviceRevocationMessage, 'signature'>): Promise<DeviceRevocationMessage> {
  const signature = await backend.sign(host.keys.signing.privateKey, revokeSigningInput(m));
  return { ...m, signature: base64urlEncode(signature) };
}

export async function verifyDeviceRevocation(backend: ShadowCryptoBackend, hostSigningPublicKey: Uint8Array, m: DeviceRevocationMessage): Promise<boolean> {
  try {
    return await backend.verify(hostSigningPublicKey, revokeSigningInput(m), base64urlDecode(m.signature));
  } catch {
    return false;
  }
}

export async function signKeyRotation(backend: ShadowCryptoBackend, host: ShadowIdentity, m: Omit<KeyRotationMessage, 'signature'>): Promise<KeyRotationMessage> {
  const signature = await backend.sign(host.keys.signing.privateKey, rotateSigningInput(m));
  return { ...m, signature: base64urlEncode(signature) };
}

export async function verifyKeyRotation(backend: ShadowCryptoBackend, hostSigningPublicKey: Uint8Array, m: KeyRotationMessage): Promise<boolean> {
  try {
    return await backend.verify(hostSigningPublicKey, rotateSigningInput(m), base64urlDecode(m.signature));
  } catch {
    return false;
  }
}

/**
 * Rotate the scope key for the set of controllers that remain after a revocation.
 * The revoked controller is excluded, so it can never receive the new key. Each
 * remaining controller receives the SAME new scope key wrapped to its own X25519
 * key — no split brain. Callers pass the per-controller agreement public keys and
 * the transcript hash captured at that controller's enrollment.
 */
export async function rotateScopeKeyForControllers(
  backend: ShadowCryptoBackend,
  input: {
    host: ShadowIdentity;
    fence: Fence; // NEW fence (post-rotation epoch)
    revokedControllerDeviceId: string;
    remaining: ReadonlyArray<{ controllerDeviceId: string; agreementPublicKey: Uint8Array; transcriptHash: Uint8Array; capabilities?: readonly ShadowCapability[] }>;
    nowMs: number;
    ttlMs?: number;
  },
): Promise<{ scopeKey: Uint8Array; scopeKeyId: string; perController: EnrollmentApproval[] }> {
  const scopeKey = backend.randomBytes(SHADOW_SCOPE_KEY_BYTES);
  const perController: EnrollmentApproval[] = [];
  for (const c of input.remaining) {
    if (c.controllerDeviceId === input.revokedControllerDeviceId) continue; // defensive: never wrap to revoked
    const approval = await approveEnrollment(backend, {
      host: input.host, fence: input.fence, controllerDeviceId: c.controllerDeviceId,
      controllerAgreementPublicKey: c.agreementPublicKey, transcriptHash: c.transcriptHash,
      sessionId: 'rotation', nowMs: input.nowMs, ttlMs: input.ttlMs, scopeKey,
      // Preserve each remaining controller's approved capability set across rotation
      // (never silently widen/downgrade). Undefined stays legacy account.read.
      capabilities: c.capabilities,
    });
    perController.push(approval);
  }
  const scopeKeyId = perController[0]?.scopeKeyId ?? 'wk_' + base64urlEncode(await structuredDigest(backend, 'maestro.shadow.scope-key.v1', [input.fence.accountId, input.fence.scopeId, scopeKey]));
  return { scopeKey, scopeKeyId, perController };
}
