/* Import fidelity — imported history must read like a live session, not a raw
   JSONL dump: thinking is its own block kind (not merged into the reply),
   tool chips carry a HUMAN label (Bash description / file path) with the raw
   command demoted to `cmd`, and harness boilerplate (meta rows, Caveat
   preambles, command-tag wrappers) never becomes a "user turn". */
import { describe, it, expect } from 'vitest';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseConversation } from './conversation-sync.js';

const T = '2026-07-01T10:00:00.000Z';

function jsonl(rows: unknown[]): string {
  const dir = mkdtempSync(join(tmpdir(), 'maestro-convsync-'));
  const file = join(dir, 'session.jsonl');
  writeFileSync(file, rows.map(r => JSON.stringify(r)).join('\n'));
  return file;
}

describe('parseConversation (claude) — transcript fidelity', () => {
  it('separates thinking from the reply and labels tools like the live UI', () => {
    const file = jsonl([
      { type: 'user', timestamp: T, message: { content: 'build me a portfolio' } },
      { type: 'assistant', timestamp: T, message: { content: [
        { type: 'thinking', thinking: 'The user wants a portfolio site…' },
        { type: 'tool_use', name: 'Bash', input: { command: 'ls -la /tmp', description: 'List temp files' } },
        { type: 'tool_use', name: 'Write', input: { file_path: '/Users/x/proj/design/index.html', content: '<html>' } },
        { type: 'text', text: 'Done — the design is live.' },
      ] } },
    ]);
    const [turn] = parseConversation('claude', { filePath: file, externalId: 'e1' });
    expect(turn.input).toBe('build me a portfolio');
    expect(turn.output).toBe('Done — the design is live.');

    const kinds = turn.transcript.map(b => b.kind);
    expect(kinds).toContain('thinking');
    const thinking = turn.transcript.find(b => b.kind === 'thinking')!;
    expect(thinking.text).toContain('portfolio site');
    const reply = turn.transcript.find(b => b.kind === 'text')!;
    expect(reply.text).toBe('Done — the design is live.'); // thinking NOT merged in

    const bash = turn.transcript.find(b => b.kind === 'tool' && b.name === 'Bash')!;
    expect(bash.text).toBe('List temp files');   // human label, not JSON args
    expect(bash.cmd).toBe('ls -la /tmp');        // raw command demoted to detail
    const write = turn.transcript.find(b => b.kind === 'tool' && b.name === 'Write')!;
    expect(write.text).toBe('~/proj/design/index.html');
  });

  it('skips meta rows, Caveat preambles, and unwraps command tags', () => {
    const file = jsonl([
      { type: 'user', timestamp: T, isMeta: true, message: { content: 'harness bookkeeping' } },
      { type: 'user', timestamp: T, message: { content: 'Caveat: The messages below were generated by the user while running local commands.' } },
      { type: 'user', timestamp: T, message: { content: '<command-message>init is analyzing…</command-message><command-name>/init</command-name>' } },
      { type: 'assistant', timestamp: T, message: { content: [{ type: 'text', text: 'ok' }] } },
      { type: 'user', timestamp: T, message: { content: 'real question' } },
      { type: 'assistant', timestamp: T, message: { content: [{ type: 'text', text: 'real answer' }] } },
    ]);
    const turns = parseConversation('claude', { filePath: file, externalId: 'e2' });
    // The /init command message survives as its own (unwrapped) turn; the meta
    // + caveat rows never become turns.
    const inputs = turns.map(t => t.input);
    expect(inputs).toContain('real question');
    expect(inputs.some(i => i.startsWith('Caveat:'))).toBe(false);
    expect(inputs.some(i => i.includes('harness bookkeeping'))).toBe(false);
    expect(inputs).toContain('/init');
  });

  it('folds tool_result-only user rows into the running assistant turn', () => {
    const file = jsonl([
      { type: 'user', timestamp: T, message: { content: 'run it' } },
      { type: 'assistant', timestamp: T, message: { content: [{ type: 'tool_use', name: 'Bash', input: { command: 'echo hi' } }] } },
      { type: 'user', timestamp: T, message: { content: [{ type: 'tool_result', content: 'hi' }] } },
      { type: 'assistant', timestamp: T, message: { content: [{ type: 'text', text: 'printed hi' }] } },
    ]);
    const turns = parseConversation('claude', { filePath: file, externalId: 'e3' });
    expect(turns).toHaveLength(1);
    expect(turns[0].transcript.map(b => b.kind)).toEqual(['tool', 'result', 'text']);
  });
});
