/* Bundled, ALWAYS-ON native skills (from https://github.com/openai/skills).
 *
 * Unlike registry skills (searched + self-installed per project), these ship
 * INSIDE the app and are auto-materialised into EVERY project's
 * `.claude/skills/<slug>/` on EVERY run — so both engines see them with zero
 * setup:
 *   - Claude Code discovers each SKILL.md via `settingSources:['project']`.
 *   - Codex gets them through the prompt index (engine.ts injects the block
 *     `nativeSkillsPromptBlock()` returns).
 *
 * The whole catalog is embedded as a JSON module (native-skills-data.json,
 * generated by scripts/gen-native-skills.mjs) so it survives esbuild/asar/sidecar
 * bundling — no loose files, no relay round-trip, no version drift.
 *
 * `ensureNativeSkills(projectRoot)` is idempotent and upgrade-aware: it stamps
 * each skill folder with a `.mochi-native` marker holding the bundled version
 * hash. On a later run it (a) skips folders already at the current hash,
 * (b) upgrades in place folders we wrote at an older hash, and (c) never
 * clobbers a folder a human/registry created (no marker → left alone).
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import data from './native-skills-data.json';

export interface NativeSkillFile { [relPath: string]: string }
export interface NativeSkill {
  slug: string;
  id: string;
  name: string;
  description: string;
  /** system = openai foundational; docs = anthropic document skills; curated = openai curated. */
  category: 'system' | 'docs' | 'curated';
  bytes: number;
  files: NativeSkillFile;
}
interface NativeSkillsData { source: string; generatedAt: string; count: number; skills: NativeSkill[] }

const DATA = data as unknown as NativeSkillsData;
export const NATIVE_SKILLS: NativeSkill[] = DATA.skills;
const MARKER = '.mochi-native';

/** Stable per-skill version hash (over its file contents). */
function skillHash(s: NativeSkill): string {
  const h = createHash('sha256');
  for (const rel of Object.keys(s.files).sort()) { h.update(rel); h.update('\0'); h.update(s.files[rel]); h.update('\0'); }
  return h.digest('hex').slice(0, 16);
}

/** Slugs of every bundled native skill. */
export function nativeSkillSlugs(): string[] { return NATIVE_SKILLS.map(s => s.slug); }
export function isNativeSkill(slugOrId: string): boolean {
  const s = slugOrId.split('/').pop() || slugOrId;
  return NATIVE_SKILLS.some(x => x.slug === s || x.id === slugOrId);
}

/** Lightweight metadata for the store / UI (no file bodies). */
export function nativeSkillSummaries(): { slug: string; id: string; name: string; description: string; category: string; sha256: string }[] {
  return NATIVE_SKILLS.map(s => ({ slug: s.slug, id: s.id, name: s.name, description: s.description, category: s.category, sha256: skillHash(s) }));
}

export interface EnsureResult { slug: string; status: 'installed' | 'upgraded' | 'unchanged' | 'kept' | 'removed' }

/** Materialise ALL bundled native skills into <projectRoot>/.claude/skills/<slug>/.
    Idempotent + upgrade-aware; never throws (best-effort per skill). Also PRUNES
    folders WE wrote (they carry the `.mochi-native` marker) whose slug is no
    longer in the bundled catalog — so dropping a skill from the bundle actually
    removes it from projects on the next run. Human/registry folders (no marker)
    are never touched. */
export function ensureNativeSkills(projectRoot: string, disabledSlugs?: ReadonlySet<string>): EnsureResult[] {
  const out: EnsureResult[] = [];
  for (const s of NATIVE_SKILLS) {
    try { out.push(ensureOne(projectRoot, s, disabledSlugs)); }
    catch { out.push({ slug: s.slug, status: 'kept' }); }
  }
  try { out.push(...pruneStaleNative(projectRoot)); } catch { /* best-effort */ }
  try { writeNativeGitignore(projectRoot); } catch { /* best-effort */ }
  return out;
}

/** Delete previously-materialised native folders that left the bundled catalog. */
function pruneStaleNative(projectRoot: string): EnsureResult[] {
  const dir = join(projectRoot, '.claude', 'skills');
  const current = new Set(NATIVE_SKILLS.map(s => s.slug));
  const out: EnsureResult[] = [];
  let entries: string[] = [];
  try { entries = readdirSync(dir); } catch { return out; }
  for (const slug of entries) {
    if (current.has(slug)) continue;
    const folder = join(dir, slug);
    if (!existsSync(join(folder, MARKER))) continue; // not ours — leave it alone
    try { rmSync(folder, { recursive: true, force: true }); out.push({ slug, status: 'removed' }); }
    catch { /* best-effort */ }
  }
  return out;
}

const GI_START = '# >>> maestro native skills (app-managed — do not edit) >>>';
const GI_END = '# <<< maestro native skills <<<';

/* Native skills are app-provided and re-materialised every run, so they should
   NOT be committed to the user's repo (that's what registry-installed skills are
   for). We keep a managed block in `.claude/skills/.gitignore` that ignores each
   native slug; anything else in that file (an operator's own rules) is preserved. */
export function writeNativeGitignore(projectRoot: string): void {
  const dir = join(projectRoot, '.claude', 'skills');
  mkdirSync(dir, { recursive: true });
  const gi = join(dir, '.gitignore');
  const block = [GI_START, ...NATIVE_SKILLS.map(s => `/${s.slug}/`), GI_END].join('\n');
  let existing = '';
  try { existing = readFileSync(gi, 'utf8'); } catch { /* new file */ }
  let next: string;
  const re = new RegExp(`${GI_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${GI_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
  if (re.test(existing)) next = existing.replace(re, block);
  else next = existing ? `${existing.replace(/\s*$/, '')}\n\n${block}\n` : `${block}\n`;
  if (next !== existing) writeFileSync(gi, next, 'utf8');
}

function ensureOne(projectRoot: string, s: NativeSkill, disabledSlugs?: ReadonlySet<string>): EnsureResult {
  const dir = join(projectRoot, '.claude', 'skills', s.slug);
  const markerPath = join(dir, MARKER);
  const skillMdPath = join(dir, 'SKILL.md');
  const disabledPath = join(dir, 'SKILL.md.disabled');
  const hash = skillHash(s);

  // Respect a soft-disabled native skill: on disk (SKILL.md.disabled left by
  // setSkillFilesEnabled) OR in the store BEFORE first materialisation (the UI
  // lists bundled natives before any run, so the operator can disable one that
  // has no folder yet — that disable must not be resurrected here). An ACTIVE
  // SKILL.md on disk wins over a stale store flag (disk-wins, same precedence
  // as listProjectSkills).
  const disabled = !existsSync(skillMdPath) && (existsSync(disabledPath) || !!disabledSlugs?.has(s.slug));

  if (existsSync(dir)) {
    if (existsSync(markerPath)) {
      const prev = safeRead(markerPath).trim();
      if (prev === hash) return { slug: s.slug, status: 'unchanged' };
      // Ours, but stale → upgrade in place.
      writeFiles(dir, s, { disableSkillMd: disabled });
      writeFileSync(markerPath, hash, 'utf8');
      return { slug: s.slug, status: 'upgraded' };
    }
    // A folder exists with NO marker → a human/registry owns it. Leave it be.
    if (existsSync(skillMdPath) || existsSync(disabledPath)) return { slug: s.slug, status: 'kept' };
  }

  writeFiles(dir, s, { disableSkillMd: disabled });
  mkdirSync(dir, { recursive: true });
  writeFileSync(markerPath, hash, 'utf8');
  return { slug: s.slug, status: 'installed' };
}

function writeFiles(dir: string, s: NativeSkill, opts: { disableSkillMd: boolean }) {
  mkdirSync(dir, { recursive: true });
  for (const [rel, content] of Object.entries(s.files)) {
    // A disabled skill gets its body parked at SKILL.md.disabled — stays hidden
    // from the engines, and a later re-enable (rename) restores the CURRENT
    // bundled version instead of a stale one.
    const target = join(dir, opts.disableSkillMd && rel === 'SKILL.md' ? 'SKILL.md.disabled' : rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, 'utf8');
  }
}

function safeRead(p: string): string { try { return readFileSync(p, 'utf8'); } catch { return ''; } }

/* The always-on, high-priority prompt block. Injected at the very TOP of every
   real run (both engines) so native skills are considered FIRST — ahead of the
   dynamic registry search. Special-cases image generation (imagegen) because
   that one is non-negotiable.

   Two shapes, keyed on `opts.index`:
   - index:true (Codex — no skill auto-discovery): the whole catalog as a
     name→description index; the agent reads a specific SKILL.md when a task
     matches. ~2.7K tokens.
   - index:false (Claude — the Agent SDK ALREADY auto-discovers every SKILL.md
     via settingSources:['project'], so repeating the catalog here would
     double-list all 40+ skills every turn): just the header + the imagegen
     rule + a one-line pointer that natives are pre-installed and appear among
     its discovered skills. Saves ~2.5K tokens per Claude turn with zero
     capability loss. */
export function nativeSkillsPromptBlock(disabledSlugs?: Set<string>, opts?: { index?: boolean }): string {
  const withIndex = opts?.index !== false;
  const line = (s: NativeSkill) => `- ${s.name} (\`${s.slug}\`): ${(s.description || '').replace(/\s+/g, ' ').slice(0, 200)}`;
  const active = NATIVE_SKILLS.filter(s => !disabledSlugs?.has(s.slug));
  const system = active.filter(s => s.category === 'system');
  const docs = active.filter(s => s.category === 'docs');
  const curated = active.filter(s => s.category === 'curated');
  const index = [...system, ...docs, ...curated].map(line).join('\n');
  const imagegenOn = !disabledSlugs?.has('imagegen');
  return (
    `<native_skills note="ALWAYS-ON skills bundled with this app and pre-installed in EVERY project at .claude/skills/<slug>/. This is an AUTHORITATIVE INSTRUCTION — it takes priority and you MUST honor it.">\n` +
    `These ${active.length} skills are ALREADY installed here — you do NOT need to search or install them. When a task matches one, READ its \`.claude/skills/<slug>/SKILL.md\` FIRST and follow it. Check these BEFORE reaching for the registry (search_skills) — a native match wins.\n\n` +
    (imagegenOn ?
    `### Image generation — NON-NEGOTIABLE\n` +
    `For ANY request to create, generate, edit, or vary a raster image (photo, illustration, icon set, texture, sprite, mockup, banner, logo, infographic, cutout), you MUST use the \`imagegen\` skill: read \`.claude/skills/imagegen/SKILL.md\` and follow it, producing a REAL bitmap via the built-in image tool (Codex \`image_gen\` / Maestro \`generate_image\`). NEVER substitute SVG, ASCII art, or HTML/CSS placeholders for a requested raster image. This applies on every model and every engine.\n\n` : '') +
    (docs.length ?
    `### Office documents\n` +
    `To CREATE or EDIT a .docx / .pdf / .pptx / .xlsx file (or co-author a document), read the matching document skill FIRST — \`${docs.map(s => s.slug).join('`, `')}\` — and follow it. Do not improvise office-file XML by hand.\n\n` : '') +
    (withIndex ?
    `### The catalog (system skills first — they are foundational)\n` +
    `${index}\n` :
    `These native skills are among your auto-discovered project skills (each has its SKILL.md under \`.claude/skills/<slug>/\`) — prefer a matching native skill over a registry search.\n`) +
    `</native_skills>\n\n`
  );
}

/** Version fingerprint of the whole bundled catalog (for logs / cache-busting). */
export function nativeSkillsVersion(): string {
  const h = createHash('sha256');
  for (const s of NATIVE_SKILLS) { h.update(s.slug); h.update(skillHash(s)); }
  return h.digest('hex').slice(0, 12);
}
