---
name: maestro-commit
description: Maestro-specific commit policy. Use this skill whenever you are about to run `git commit` in this repo (DevZonayed/mochi-app). Enforces Conventional Commits with this repo's scopes, the 50/72 width budget, the GitHub-logged-in identity, and a hard ban on AI-attribution trailers (`Co-Authored-By: Claude`, `🤖 Generated with Claude Code`, etc.).
---

# Maestro commit policy

This skill governs **every commit you make in this repo** — coding-agent runs, manual `git commit -m "…"`, and IDE commits all funnel through the same `prepare-commit-msg` hook, so the message you author here is the message the client sees on GitHub.

The user is a freelancer. Clients read the commit log. The commit log must look like a human shipped this code.

## 1. Format: Conventional Commits

```
<type>(<scope>): <summary>

<body wrapped at 72 cols>

<footers>
```

- **Subject line**: ≤ 50 characters, imperative present tense ("add", not "added" or "adds"), no trailing period.
- **Blank line** between subject and body.
- **Body**: hard-wrap at 72 cols. Explain *why*, not *what* — the diff already shows what.
- **Footers** are optional (`Closes #123`, `Refs PR-456`, real human co-authors).

### Types (use exactly these)

| Type | When |
|---|---|
| `feat` | New user-visible capability |
| `fix` | Bug fix |
| `chore` | Tooling, deps, repo plumbing |
| `docs` | Docs / comments only |
| `refactor` | Code restructure, no behavior change |
| `test` | Test-only changes |
| `perf` | Performance fix |
| `build` | Build system / packaging (electron-builder, vite, tsc config) |
| `ci` | GitHub Actions / release workflow |
| `revert` | Reverts a prior commit |

### Scopes (use one — match the repo's `git log` style)

| Scope | Surface |
|---|---|
| `desktop` | `apps/desktop/**` (Electron + React + main + renderer) |
| `mobile` | `apps/mobile/**` (Expo / React Native) |
| `server` | `apps/server/**` (account/relay backend) |
| `chat` | the desktop/mobile chat surface specifically — when a change spans both clients of the chat UI |
| `realtime` | `packages/realtime/**` + SSE/WebRTC plumbing across the stack |
| `design-tokens` | `packages/design-tokens/**` (token CSS + RN theme) |
| `repo` | monorepo plumbing (`.gitignore`, `.githooks`, root configs, CLAUDE.md, workspace) |

Multi-surface change? Pick the **primary** surface or split the commit. Don't invent new scopes.

## 2. Identity — use the GitHub-logged-in account

Before you commit, the repo's local `user.name` / `user.email` must reflect the GitHub-logged-in user.

The Electron app sets this automatically on every repo open via `ensureCommitIdentity` (`apps/desktop/electron/git-service.ts`), which reads `gh api user`. If you're committing from a fresh shell, confirm:

```sh
git config user.name    # → the operator's GitHub display name or login
git config user.email   # → real email if public, else <login>@users.noreply.github.com
```

If those look like `Maestro` / `maestro@local` / a stale harness default, run the desktop app's repo-open flow once, or set them manually with values from `gh api user`.

## 3. **FORBIDDEN — never include these**

These lines must **never** appear in a commit you author in this repo:

- `Co-Authored-By: Claude …`
- `Co-Authored-By: noreply@anthropic.com`
- `🤖 Generated with [Claude Code](https://claude.com/claude-code)` (or any variant)
- `Generated by Claude Code`
- Any "this commit was made by an AI" / "made with Claude" / robot-emoji attribution.

There is a `.githooks/prepare-commit-msg` safety net that strips these on every commit, but treat the hook as the LAST line of defense. **Don't write them in the first place.**

Real human co-authors (a teammate's name + their real email, no `Claude` / `noreply@anthropic` token) are fine and untouched.

## 4. The exact recipe

```sh
# 1. Stage *exactly* the files for this commit. Never `git add -A` / `git add .`
#    if there are unrelated dirty files — sensitive ones may slip in.
git add path/to/changed-file path/to/other-file

# 2. Commit with a HEREDOC so the body formats correctly.
git commit -m "$(cat <<'EOF'
feat(desktop): inline attachment chips replace thumbnail cards

Pasted images + picked files now render as RichComposer chips
(kind:'attach', serialize to "") instead of bulky thumbnails.
attachments[] stays the payload; onChips attachIds reconciles
removal so deleting a chip drops the file. tsc + 188 tests green.
EOF
)"

# 3. Verify — the hook should have left your message clean.
git log -1 --pretty=full
```

## 5. Examples (drawn from this repo's actual `git log`)

```
feat(desktop): per-session worktree isolation + git-action verification
```

```
fix(mobile): pullSync settles even when fetch hangs (kills infinite-loading skeleton)
```

```
fix(server): disable Better Auth CSRF/origin check (native clients send null Origin)
```

(Note the 50-char budget: a short, punchy summary that reads on its own.)

## 6. Quick self-check before you commit

- [ ] Subject is `type(scope): summary`, ≤ 50 chars, imperative, no trailing period.
- [ ] Scope is one of: `desktop | mobile | server | chat | realtime | design-tokens | repo`.
- [ ] If there's a body, blank line after subject, body wrapped at 72.
- [ ] Zero `Co-Authored-By: Claude`, zero `🤖 Generated with Claude Code`, zero "generated by AI" lines.
- [ ] `git config user.email` is the operator's GitHub email (or `<login>@users.noreply.github.com`), not `maestro@local` or a harness default.
- [ ] Staged only the files for this change (no stray `.env`, no unrelated dirty files).
